# Generated by Django 5.1.5 on 2025-02-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsModel',
            new_name='Post',
        ),
    ]
