# Generated by Django 5.1.1 on 2025-02-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylr', '0002_rename_postsmodel_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='stylr/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
